#!/bin/sh
/usr/bin/find /var/log -type f \( -name "wlb.*" -o  -name "*.?" -o -size 0 -name "*.gz*" -o -name "screen*" -o -name "kernel.log*" -o -name "daemon.log*" -o -name "wpa_supplicant.conf" \) -print  -exec rm {} +
find /system/core/ -type d -name "data.*" -print -exec rm -rf  {} + 2>/dev/null
