[Definition]

actionstart =
actionstop =
actioncheck = nft list set inet filter f2b_sshd
actionban = nft add element inet filter f2b_sshd { <ip> timeout <bantime>s }
actionunban = nft delete element inet filter f2b_sshd { <ip> }

[Init]
