flush ruleset

table inet filter {
    set f2b_sshd {
        type ipv4_addr
        flags timeout
    }

    chain input {
        type filter hook input priority 0; policy drop;

        iif "lo" accept

        ip saddr @f2b_sshd drop

        ct state established,related accept

        ip protocol icmp accept
        ip6 nexthdr icmpv6 accept

        tcp dport 22 accept

        counter log prefix "nftables-drop: " drop
    }
}
