[Definition]

failregex = ^.*sshd\[\d+\]: Failed password for .* from <HOST> port \d+ ssh2.*$
            ^.*sshd\[\d+\]: Failed password for invalid user .* from <HOST> port \d+ ssh2.*$
            ^.*sshd\[\d+\]: Invalid user .* from <HOST> port \d+.*$
            ^.*sshd\[\d+\]: Connection closed by invalid user .* <HOST> port \d+.*$
            ^.*sshd\[\d+\]: error: maximum authentication attempts exceeded for .* from <HOST> port \d+ ssh2.*$

ignoreregex =
