# Distro for Sirius images based on Poky

require conf/distro/poky.conf

DISTRO = "sirius"
DISTRO_NAME = "Sirius Embedded Linux"
DISTRO_VERSION = "1.0+snapshot-${DATE}"
DISTRO_CODENAME = "sirius"
MAINTAINER = "Prashant Divate <diwateprashant@gmail.com>"

POKY_DEFAULT_EXTRA_RDEPENDS = ""
POKY_DEFAULT_EXTRA_RRECOMMENDS = ""

# Optional meta-sirius features
SIRIUS_ENABLE_SHELLHUB ?= "0"

# Use systemd as default init manager
DISTRO_FEATURES:append = " systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"

PACKAGE_CLASSES ?= "package_ipk"

ROOT_HOME = "/root"

# Avoid pulseaudio backfill unless explicitly needed
DISTRO_FEATURES_BACKFILL_CONSIDERED += " pulseaudio"
