#!/bin/sh

# Regular Colors
Red='\033[0;31m'          # Red
Back='\033[0m'            # No Color

log() {
    echo -e "$@"
}

fatal() {
  echo ""
  echo -e "${Red}[Error]:${Back} $@"
  echo ""
}

COMMIT_MSG_FILE=$1

# Throw error if the message is empty
if [[ -z $(grep '[^[:space:]]' $COMMIT_MSG_FILE) ]] ; then
  fatal "You can't just commit without a message !!" >&2
  exit 1
fi

COMMIT_MSG=$(cat "$1")
MSG_PATTERN="^recipes-[a-zA-Z]+: $@"

# Check the commit message format
if [[ ! $COMMIT_MSG =~ $MSG_PATTERN ]]; then
  fatal "Error: Commit message format is incorrect."
  fatal "Format should be: recipes-<name>: <message>"
  echo "Example: recipes-example: GOP-123 Fix something"
  exit 1
fi
